## General pipeline parameters:
## For optional parameters either leave empty string ("") or comment out ("#") the parameter

# Name of the pipeline:
pipeline: "vector-analysis"

# working directory (required):
workdir: "/path/to/workdir"

# prefix of all output files:
sample_name: "vector"

# reference genome as fasta (required)
genome: "/path/to/reference.fa"

# PacBio HiFi reads (as FASTA)
CCS_fasta: "/path/to/hifi_reads.fa"

# Options passed to Sniffles (optional):
sniffles_opts: ""

# threads (optional; default 10)
threads: 100